import type { PlasmaPreset } from './types';

export const plasmaPresets = {
  nebula: {
    label: 'Nebula',
    concept: 'Nebulosa cósmica com manchas roxas-azuladas e brilho difuso.',
    color1: '#7c3aed',
    color2: '#0ea5e9',
    color3: '#f0abfc',
    speed: 0.22,
    intensity: 1.08,
    scale: 1,
    complexity: 4,
    saturation: 1.2,
  },
  lava: {
    label: 'Lava',
    concept: 'Fluxo vulcânico com veios vermelhos, laranja e núcleo branco.',
    color1: '#dc2626',
    color2: '#f97316',
    color3: '#fef3c7',
    speed: 0.32,
    intensity: 1.3,
    scale: 1.2,
    complexity: 3,
    saturation: 1.4,
  },
  electric: {
    label: 'Electric',
    concept: 'Descargas elétricas azul-brancas com bordas violeta.',
    color1: '#2563eb',
    color2: '#7dd3fc',
    color3: '#f8fafc',
    speed: 0.48,
    intensity: 1.5,
    scale: 0.8,
    complexity: 5,
    saturation: 0.8,
  },
  aurora: {
    label: 'Aurora B.',
    concept: 'Cortinas verdes-rosa com movimento ondulante e etéreo.',
    color1: '#059669',
    color2: '#db2777',
    color3: '#a7f3d0',
    speed: 0.16,
    intensity: 0.9,
    scale: 1.1,
    complexity: 3,
    saturation: 1.0,
  },
  acid: {
    label: 'Acid',
    concept: 'Manchas psicodélicas neon com contraste extremo e pulsação.',
    color1: '#84cc16',
    color2: '#d946ef',
    color3: '#fef08a',
    speed: 0.4,
    intensity: 1.6,
    scale: 1.5,
    complexity: 6,
    saturation: 1.6,
  },
} satisfies Record<string, PlasmaPreset>;

export type PlasmaPresetId = keyof typeof plasmaPresets;
