import type { StarfieldPreset } from './types';

export const starfieldPresets = {
  cruise: {
    label: 'Cruise',
    concept: 'Campo estelar equilibrado para fundos espaciais discretos.',
    color1: '#bfdbfe',
    color2: '#67e8f9',
    speed: 0.18,
    intensity: 0.92,
    density: 900,
    depth: 18,
    spread: 12,
    pointSize: 18,
  },
  deep: {
    label: 'Deep',
    concept: 'Mais profundidade, brilho baixo e estrelas afastadas.',
    color1: '#c4b5fd',
    color2: '#93c5fd',
    speed: 0.1,
    intensity: 0.64,
    density: 1100,
    depth: 26,
    spread: 15,
    pointSize: 14,
  },
  warp: {
    label: 'Warp',
    concept: 'Velocidade alta, particulas densas e leitura de deslocamento.',
    color1: '#f8fafc',
    color2: '#22d3ee',
    speed: 0.72,
    intensity: 1.18,
    density: 1400,
    depth: 20,
    spread: 11,
    pointSize: 22,
  },
  quiet: {
    label: 'Quiet',
    concept: 'Poucas estrelas, baixo contraste e movimento quase imovel.',
    color1: '#e2e8f0',
    color2: '#a7f3d0',
    speed: 0.06,
    intensity: 0.5,
    density: 620,
    depth: 16,
    spread: 14,
    pointSize: 12,
  },
  cyan: {
    label: 'Cyan',
    concept: 'Brilho frio para cenas tecnicas e composicoes com UI.',
    color1: '#a5f3fc',
    color2: '#38bdf8',
    speed: 0.28,
    intensity: 1.02,
    density: 1000,
    depth: 18,
    spread: 10,
    pointSize: 17,
  },
} satisfies Record<string, StarfieldPreset>;

export type StarfieldPresetId = keyof typeof starfieldPresets;
