import type { LavaLampPreset } from './types';

export const lavaLampPresets = {
  retro: {
    label: 'Retro',
    concept: 'Classic lava lamp with warm blobs floating on dark background.',
    color1: '#ef4444',
    color2: '#f97316',
    color3: '#fde68a',
    speed: 0.18,
    intensity: 1.1,
    blobCount: 5,
    scale: 1.0,
    glow: 0.6,
  },
  neon: {
    label: 'Neon',
    concept: 'Electric cyan and magenta blobs with bright edge glow.',
    color1: '#06b6d4',
    color2: '#d946ef',
    color3: '#f8fafc',
    speed: 0.28,
    intensity: 1.3,
    blobCount: 6,
    scale: 0.9,
    glow: 0.9,
  },
  abyss: {
    label: 'Abyss',
    concept: 'Deep ocean greens merging on a dark teal canvas.',
    color1: '#14b8a6',
    color2: '#059669',
    color3: '#d1fae5',
    speed: 0.14,
    intensity: 0.9,
    blobCount: 4,
    scale: 1.1,
    glow: 0.5,
  },
  ultraviolet: {
    label: 'Ultraviolet',
    concept: 'Violet and pink plasma orbs with hot white cores.',
    color1: '#a855f7',
    color2: '#ec4899',
    color3: '#fdf4ff',
    speed: 0.32,
    intensity: 1.2,
    blobCount: 5,
    scale: 0.85,
    glow: 0.85,
  },
  ember: {
    label: 'Ember',
    concept: 'Smoldering amber orbs rising through dark smoke.',
    color1: '#f59e0b',
    color2: '#dc2626',
    color3: '#fffbeb',
    speed: 0.22,
    intensity: 1.05,
    blobCount: 4,
    scale: 1.15,
    glow: 0.7,
  },
  frost: {
    label: 'Frost',
    concept: 'Cold blue-white blobs drifting like ice under water.',
    color1: '#38bdf8',
    color2: '#e0f2fe',
    color3: '#f8fafc',
    speed: 0.12,
    intensity: 0.85,
    blobCount: 4,
    scale: 1.2,
    glow: 0.55,
  },
  cosmic: {
    label: 'Cosmic',
    concept: 'Nebula-like merging blobs with star-like brightness.',
    color1: '#6366f1',
    color2: '#8b5cf6',
    color3: '#c4b5fd',
    speed: 0.2,
    intensity: 1.15,
    blobCount: 6,
    scale: 1.0,
    glow: 0.75,
  },
  honey: {
    label: 'Honey',
    concept: 'Golden amber blobs with soft warm highlights.',
    color1: '#d97706',
    color2: '#fbbf24',
    color3: '#fef3c7',
    speed: 0.1,
    intensity: 0.95,
    blobCount: 3,
    scale: 1.3,
    glow: 0.45,
  },
} satisfies Record<string, LavaLampPreset>;

export type LavaLampPresetId = keyof typeof lavaLampPresets;
