import type { FluidGradientPreset } from './types';

export const fluidGradientPresets = {
  prism: {
    label: 'Prism',
    concept: 'Gradiente liquido com transicoes frias e brilho editorial.',
    color1: '#22d3ee',
    color2: '#8b5cf6',
    color3: '#f0abfc',
    speed: 0.24,
    intensity: 1.08,
    scale: 1.12,
    distortion: 0.58,
    contrast: 1.1,
  },
  lagoon: {
    label: 'Lagoon',
    concept: 'Azuis e verdes densos para fundos calmos e profundos.',
    color1: '#0891b2',
    color2: '#10b981',
    color3: '#ccfbf1',
    speed: 0.16,
    intensity: 0.82,
    scale: 0.92,
    distortion: 0.42,
    contrast: 0.92,
  },
  ember: {
    label: 'Ember',
    concept: 'Calor organico com nucleo alaranjado e bordas magenta.',
    color1: '#fb7185',
    color2: '#f97316',
    color3: '#fef3c7',
    speed: 0.3,
    intensity: 1.16,
    scale: 1,
    distortion: 0.7,
    contrast: 1.22,
  },
  violet: {
    label: 'Violet',
    concept: 'Movimento amplo e dramatico para demonstrar amplitude de cor.',
    color1: '#7c3aed',
    color2: '#2563eb',
    color3: '#f5d0fe',
    speed: 0.22,
    intensity: 1,
    scale: 1.34,
    distortion: 0.64,
    contrast: 1.26,
  },
  mint: {
    label: 'Mint',
    concept: 'Preset claro, suave e de baixa saturacao para leitura de UI.',
    color1: '#5eead4',
    color2: '#bae6fd',
    color3: '#f8fafc',
    speed: 0.12,
    intensity: 0.68,
    scale: 0.78,
    distortion: 0.28,
    contrast: 0.84,
  },
  plasma: {
    label: 'Plasma',
    concept: 'Manchas compactas, alto contraste e pulsacao mais tecnica.',
    color1: '#ef4444',
    color2: '#06b6d4',
    color3: '#fde047',
    speed: 0.42,
    intensity: 1.24,
    scale: 1.62,
    distortion: 0.86,
    contrast: 1.42,
  },
} satisfies Record<string, FluidGradientPreset>;

export type FluidGradientPresetId = keyof typeof fluidGradientPresets;
