import type { AuroraPreset } from './types';

export const auroraPresets = {
  polar: {
    label: 'Polar',
    concept: 'Cortinas verdes e violetas, base canonica do projeto.',
    color1: '#14b8a6',
    color2: '#7c3aed',
    color3: '#d1fae5',
    speed: 0.32,
    intensity: 1.08,
    bandScale: 1.15,
    distortion: 0.72,
    contrast: 1.12,
  },
  dusk: {
    label: 'Dusk',
    concept: 'Faixas quentes para transicoes de marca e fundos editoriais.',
    color1: '#f97316',
    color2: '#be185d',
    color3: '#fde68a',
    speed: 0.2,
    intensity: 0.92,
    bandScale: 0.86,
    distortion: 0.48,
    contrast: 1.2,
  },
  glacial: {
    label: 'Glacial',
    concept: 'Azuis frios com movimento lento e baixo contraste.',
    color1: '#38bdf8',
    color2: '#a7f3d0',
    color3: '#e0f2fe',
    speed: 0.18,
    intensity: 0.76,
    bandScale: 0.72,
    distortion: 0.36,
    contrast: 0.92,
  },
  ion: {
    label: 'Ion',
    concept: 'Energia eletrica, alto brilho e curvas mais comprimidas.',
    color1: '#22d3ee',
    color2: '#2563eb',
    color3: '#f8fafc',
    speed: 0.58,
    intensity: 1.24,
    bandScale: 1.62,
    distortion: 0.92,
    contrast: 1.36,
  },
  ember: {
    label: 'Ember',
    concept: 'Luz mineral com bordas rubi e centro incandescente.',
    color1: '#f43f5e',
    color2: '#f59e0b',
    color3: '#fff7ed',
    speed: 0.42,
    intensity: 1.18,
    bandScale: 1.04,
    distortion: 0.64,
    contrast: 1.28,
  },
  ultraviolet: {
    label: 'Ultraviolet',
    concept: 'Preset mais dramatico para demonstrar amplitude cromatica.',
    color1: '#a855f7',
    color2: '#ec4899',
    color3: '#f5d0fe',
    speed: 0.36,
    intensity: 1.14,
    bandScale: 1.34,
    distortion: 0.78,
    contrast: 1.32,
  },
  specter: {
    label: 'Specter',
    concept: 'Baixa saturacao, leitura suave e movimento quase atmosferico.',
    color1: '#94a3b8',
    color2: '#2dd4bf',
    color3: '#f8fafc',
    speed: 0.14,
    intensity: 0.58,
    bandScale: 0.58,
    distortion: 0.24,
    contrast: 0.78,
  },
  signal: {
    label: 'Signal',
    concept: 'Linhas estreitas e responsivas para interfaces tecnicas.',
    color1: '#84cc16',
    color2: '#06b6d4',
    color3: '#ecfccb',
    speed: 0.68,
    intensity: 0.96,
    bandScale: 1.95,
    distortion: 0.42,
    contrast: 1.42,
  },
} satisfies Record<string, AuroraPreset>;

export type AuroraPresetId = keyof typeof auroraPresets;
