import type { VortexPreset } from './types';

export const vortexPresets = {
  whirlpool: {
    label: 'Whirlpool',
    concept: 'Espiral azul profundo com centro luminoso e arrasto suave.',
    color1: '#0ea5e9',
    color2: '#1e3a5f',
    color3: '#7dd3fc',
    speed: 0.28,
    intensity: 1.12,
    arms: 3,
    twist: 0.72,
    zoom: 1,
  },
  tunnel: {
    label: 'Tunnel',
    concept: 'Túnel psicodélico com anéis concêntricos pulsantes.',
    color1: '#a855f7',
    color2: '#059669',
    color3: '#fde047',
    speed: 0.18,
    intensity: 1.3,
    arms: 1,
    twist: 1.2,
    zoom: 1.4,
  },
  galaxy: {
    label: 'Galaxy',
    concept: 'Núcleo galáctico com braços espirais densos e poeira cósmica.',
    color1: '#ec4899',
    color2: '#6366f1',
    color3: '#f0abfc',
    speed: 0.14,
    intensity: 0.96,
    arms: 5,
    twist: 0.58,
    zoom: 0.86,
  },
  portal: {
    label: 'Portal',
    concept: 'Anel energético com rotação diferencial e brilho interno.',
    color1: '#06b6d4',
    color2: '#f43f5e',
    color3: '#fef9c3',
    speed: 0.38,
    intensity: 1.42,
    arms: 4,
    twist: 0.42,
    zoom: 0.72,
  },
  cyclone: {
    label: 'Cyclone',
    concept: 'Vórtice de alta velocidade com estrias radiais e contraste extremo.',
    color1: '#8b5cf6',
    color2: '#0f172a',
    color3: '#38bdf8',
    speed: 0.48,
    intensity: 1.6,
    arms: 2,
    twist: 1.6,
    zoom: 1.2,
  },
} satisfies Record<string, VortexPreset>;

export type VortexPresetId = keyof typeof vortexPresets;
